<?php
// Copyright 1999-2016. Parallels IP Holdings GmbH. All Rights Reserved.
?>
<?php echo $this->form; ?>

<script type="text/javascript">
//<![CDATA[
Jsw.onReady(function() {
    tinymce.init({
        selector:'textarea',
        plugins: [
            "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
            "searchreplace wordcount visualblocks visualchars code fullscreen fullpage insertdatetime media",
            "nonbreaking table contextmenu directionality emoticons template paste textcolor"
        ],
        relative_urls: true,
        document_base_url: 'http://<?php echo $this->domainName ?>/'
    });

    $('fileData').up('form').down('button[name="send"]').observe('click', function() {
        $('fileData').value = tinymce.activeEditor.getContent();
    });
});
//]]>
</script>
