<?php
// Copyright 1999-2024. WebPros International GmbH. All rights reserved.
?>
<?php echo $this->form; ?>

<script type="text/javascript">
//<![CDATA[
Jsw.onReady(function() {
    tinymce.init({
        selector:'textarea',
        plugins: [
            'advlist', 'autolink', 'link', 'image', 'lists', 'charmap', 'preview', 'anchor', 'pagebreak',
            'searchreplace', 'wordcount', 'visualblocks', 'visualchars', 'code', 'fullscreen', 'insertdatetime', 'media',
            'nonbreaking', 'table', 'directionality', 'emoticons',
        ],
        relative_urls: true,
        document_base_url: 'http://<?php echo $this->domainName ?>/'
    });

    $('fileData').up('form').down('button[name="send"]').observe('click', function() {
        $('fileData').value = tinymce.activeEditor.getContent();
    });
});
//]]>
</script>
